version: v1.1.0

serve:
  public:
    cors:
      enabled: true

selfservice:
  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: false
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    settings:
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      use: code

    verification:
      enabled: true
      use: code

    login:
      lifespan: 10m

    registration:
      lifespan: 10m
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  format: text

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/kratos/schemas/identity.schema.json

feature_flags:
  use_continue_with_transitions: true
